export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILED = 'GET_MOVIES_FAILED';
export const MOVIES_IS_LOADING = 'MOVIES_IS_LOADING';

export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS';
export const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';

export const SORT_BY_CHANGED = 'SORT_BY_CHANGED';
export const FILTER_BY_CHANGED = 'FILTER_BY_CHANGED';